#! /bin/bash

day_11 () {
  cd day_11 && gcc main.c -o main && time -h ./main

}

general () {
  cd $1 && gcc part1.c -o part1 && time -l ./part1
}

function_exists() {
  declare -f -F $1 > /dev/null
  return $?
}

dir=$(printf "day_%02d\n" $1)
function_exists $dir && "$dir" || general $dir
