# Name of the snippet:
TARGET_NAME = program

# Specify all source files:
SOURCES = part1.c
# SOURCES += ../common/compare.c
# SOURCES += ../utils/queue.c

# Specify all include paths:
INCLUDES = -I.
INCLUDES += -I../common

# Specify defines:
DEFINES =
#DEFINES += ...

include ../global.mk
